//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace meepMoop.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using meepMoop.Utils;
    
    /// <summary>
    /// Order Status
    /// </summary>
    public enum OrderStatus
    {
        [JsonProperty("placed")]
        Placed,
        [JsonProperty("approved")]
        Approved,
        [JsonProperty("delivered")]
        Delivered,
    }

    public static class OrderStatusExtension
    {
        public static string Value(this OrderStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static OrderStatus ToEnum(this string value)
        {
            foreach(var field in typeof(OrderStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is OrderStatus)
                    {
                        return (OrderStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum OrderStatus");
        }
    }

}