//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace meepMoop.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using meepMoop.Models.Components;
    using meepMoop.Utils;
    
    public class Order
    {

        [JsonProperty("id")]
        public long? Id { get; set; }

        [JsonProperty("petId")]
        public long? PetId { get; set; }

        [JsonProperty("quantity")]
        public int? Quantity { get; set; }

        [JsonProperty("shipDate")]
        public DateTime? ShipDate { get; set; }

        /// <summary>
        /// Order Status
        /// </summary>
        [JsonProperty("status")]
        public OrderStatus? Status { get; set; }

        [JsonProperty("complete")]
        public bool? Complete { get; set; }
    }
}