//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace meepMoop.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using meepMoop.Utils;
    
    /// <summary>
    /// pet status in the store
    /// </summary>
    public enum PetStatus
    {
        [JsonProperty("available")]
        Available,
        [JsonProperty("pending")]
        Pending,
        [JsonProperty("sold")]
        Sold,
    }

    public static class PetStatusExtension
    {
        public static string Value(this PetStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static PetStatus ToEnum(this string value)
        {
            foreach(var field in typeof(PetStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is PetStatus)
                    {
                        return (PetStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum PetStatus");
        }
    }

}