//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace meepMoop.Models.Errors
{
    using Newtonsoft.Json;
    using System;
    using System.Net.Http;
    using meepMoop.Models.Components;
    using meepMoop.Utils;

    public class ApiErrorInvalidInputPayload
    {
        [JsonProperty("status")]
        public int Status { get; set; } = default!;

        [JsonProperty("error")]
        public string Error { get; set; } = default!;

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;
    }

    /// <summary>
    /// Not Found error
    /// </summary>
    public class ApiErrorInvalidInput : PetstoreException
    {
        /// <summary>
        ///  The original data that was passed to this exception.
        /// </summary>
        public ApiErrorInvalidInputPayload Payload { get; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use ApiErrorInvalidInput.Payload.Status instead.")]
        public int Status { get; set; } = default!;

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use ApiErrorInvalidInput.Payload.Error instead.")]
        public string Error { get; set; } = default!;

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use ApiErrorInvalidInput.Payload.HttpMeta instead.")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        public ApiErrorInvalidInput(
            ApiErrorInvalidInputPayload payload,
            HttpRequestMessage request,
            HttpResponseMessage response,
            string body
        ): base("API error occurred", request, response, body)
        {
           Payload = payload;

           #pragma warning disable CS0618
           Status = payload.Status;
           Error = payload.Error;
           HttpMeta = payload.HttpMeta;
           #pragma warning restore CS0618
        }
    }

}