//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace meepMoop.Models.Requests
{
    using meepMoop.Utils;
    
    public class DeleteUserRequest
    {

        /// <summary>
        /// The name that needs to be deleted
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=username")]
        public string Username { get; set; } = default!;
    }
}