//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace meepMoop.Models.Requests
{
    using meepMoop.Utils;
    
    public class DeletePetRequest
    {

        [SpeakeasyMetadata("header:style=simple,explode=false,name=api_key")]
        public string? ApiKey { get; set; }

        /// <summary>
        /// Pet id to delete
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=petId")]
        public long PetId { get; set; } = default!;
    }
}