//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace meepMoop.Models.Requests
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using meepMoop.Models.Components;
    using meepMoop.Utils;
    
    public class FindPetsByStatusResponse
    {

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        /// <summary>
        /// successful operation
        /// </summary>
        public List<Models.Components.Pet>? Pets { get; set; }
    }
}