//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace meepMoop.Models.Requests
{
    using System.Collections.Generic;
    using meepMoop.Utils;
    
    public class FindPetsByTagsRequest
    {

        /// <summary>
        /// Tags to filter by
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=tags")]
        public List<string>? Tags { get; set; }
    }
}