//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace meepMoop.Models.Requests
{
    using meepMoop.Models.Requests;
    using meepMoop.Utils;
    
    public class FindPetsByStatusRequest
    {

        /// <summary>
        /// Status values that need to be considered for filter
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=status")]
        public Status? Status { get; set; } = meepMoop.Models.Requests.Status.Available;
    }
}