//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace meepMoop.Models.Requests
{
    using meepMoop.Utils;
    
    public class GetOrderByIdRequest
    {

        /// <summary>
        /// ID of order that needs to be fetched
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orderId")]
        public long OrderId { get; set; } = default!;
    }
}