//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace meepMoop.Models.Requests
{
    using meepMoop.Utils;
    
    public class LoginUserRequest
    {

        /// <summary>
        /// The user name for login
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=username")]
        public string? Username { get; set; }

        /// <summary>
        /// The password for login in clear text
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=password")]
        public string? Password { get; set; }
    }
}