//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace meepMoop.Models.Requests
{
    using meepMoop.Models.Components;
    using meepMoop.Utils;
    
    public class UpdateUserRequest
    {

        /// <summary>
        /// name that needs to be updated
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=username")]
        public string Username { get; set; } = default!;

        /// <summary>
        /// Update an existent user in the store
        /// </summary>
        [SpeakeasyMetadata("request:mediaType=application/json")]
        public Models.Components.User? User { get; set; }
    }
}