//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace meepMoop.Models.Requests
{
    using meepMoop.Utils;
    
    public class UploadFileRequest
    {

        /// <summary>
        /// ID of pet to update
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=petId")]
        public long PetId { get; set; } = default!;

        /// <summary>
        /// Additional Metadata
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=additionalMetadata")]
        public string? AdditionalMetadata { get; set; }

        [SpeakeasyMetadata("request:mediaType=application/octet-stream")]
        public byte[]? RequestBody { get; set; }
    }
}